name: isis
channels:
- conda-forge
- defaults
- jlaura
dependencies:
- ca-certificates=2016.8.2=3
- certifi=2016.8.2=py35_0
- curl=7.49.1=1
- expat=2.1.0=2
- freexl=1.0.2=1
- geos=3.4.2=2
- giflib=5.1.2=1
- h5py=2.6.0=np110py35_6
- hdf4=4.2.12=0
- hdf5=1.8.17=2
- icu=56.1=4
- jpeg=9b=0
- json-c=0.12=0
- kealib=1.4.6=3
- libdap4=3.18.0=2
- libiconv=1.14=3
- libnetcdf=4.4.1=0
- libpng=1.6.24=0
- libspatialite=4.3.0a=9
- libtiff=4.0.6=6
- libuuid=1.0.3=1
- libxml2=2.9.4=0
- ncurses=5.9=8
- openjpeg=2.1.0=6
- openssl=1.0.2h=2
- pandas=0.18.1=np110py35_1
- pip=8.1.2=py35_0
- postgresql=9.5.4=2
- proj.4=4.9.2=0
- protobuf=3.0.0b2=py35_0
- python=3.5.2=2
- python-dateutil=2.5.3=py35_0
- pytz=2016.6.1=py35_0
- pyyaml=3.11=py35_0
- readline=6.2=0
- setuptools=25.1.6=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=1
- tk=8.5.19=0
- wheel=0.29.0=py35_0
- xerces-c=3.1.4=2
- xmltodict=0.10.2=py35_0
- xz=5.2.2=0
- yaml=0.1.6=0
- zlib=1.2.8=3
- plio=0.1.0=py35_0
- pvl=0.2.0=py35_0
- gdal=2.1.1=np110py35_1
- mkl=11.3.3=0
- numpy=1.10.4=py35_2
- sqlalchemy=1.0.13=py35_0
- pip:
  - certifi==2016.8.2
  - gdal==2.1.1
  - h5py==2.6.0
  - pandas==0.18.1
  - pip==8.1.2
  - plio==0.1.0
  - protobuf==3.0.0b2
  - pvl==0.2.0
  - python-dateutil==2.5.3
  - pytz==2016.6.1
  - pyyaml==3.11
  - setuptools==25.1.6
  - six==1.10.0
  - wheel==0.29.0
  - xmltodict==0.10.2
